### ISSUE TITLE
Creating CRD objects for Organization Dashboards and Datasources

### ISSUE THREAD

**Issue by unitygilles** [k8spin/grafana-multi-tenant-operator#15]
Hello maintainers,

I would like to know what are your thoughts of having CRDs for Dashboards and Datasources. Let me explain the reasoning behind it.

This new CRD would allow dev teams to deploy their dashboards in their given organization (well-known organization name) alongside their Helm Charts, in the same self-serve manner as they deploy ServiceMonitors with their Helm chart to get their metrics scrapped in a Prometheus Operator setup.

Same thing could be done for organization datasources, if they deploy their own monitoring stack.

I could see something like this:

```
apiVersion: grafana.k8spin.cloud/v1
kind: Dashboard
metadata:
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  name: web-app-health
  namespace: default
spec:
  organizations:
  - example.com
  jsonDashboard: |-
    {
      ...
    }
```

This could coexist with the current Organization CRD, if desired. Currently, the operator only supports adding dashboards using the `Org.spec.dashboards` list. Having several dashboards in there becomes easily unreadable and increases the object overall size.

Let me know what you guys think, and thanks again for taking the time to review this issue. 😄

**Comment by angelbarrera92** [comment]
Ciao @unitygilles!

I think it is a good idea. As you said, having an Organization with a lot of data sources could be unmanageable. 
That being said, I like the approach of having the same dashboard/data source as CRD assigned to multiple Organizations. 

I would like to maintain both approaches:

- Let the user create an organization with preconfigured dashboards/data sources.
- Let the user create data sources and/or dashboard using a CRD. (as you propose).

Also, to maintain the same structure, I would suggest using the following CRD (as an example):

```yaml
apiVersion: grafana.k8spin.cloud/v1
kind: Dashboard
metadata:
  name: web-app-health
  namespace: default
spec:
  organizations:
  - example.com
  dashboard:
    name: example
    data: |
      {
        "type": "prometheus",
        "access": "proxy",
        "url": "http://prometheus.monitoring:9090"
      }
```

What do you think @paurosello?

**Comment by paurosello** [comment]
I think that looks fine, I prefer each dashboard to live on a separate CRD as otherwise the CR could become too big and hit the size limit if someone goes wild with the amount of dashboards.

For the sake of simplicity we might want to deprecate datasources/dashboards defined in the Organization CRD but let's go step by step :)

**Comment by angelbarrera92** [comment]
> I think that looks fine, I prefer each dashboard to live on a separate CRD as otherwise the CR could become too big and hit the size limit if someone goes wild with the amount of dashboards.
> 
> For the sake of simplicity we might want to deprecate datasources/dashboards defined in the Organization CRD but let's go step by step :)

Exactly, I think that we should mark the datasource/dashboard defined in the org CRD as deprecated.

@unitygilles are you going to take care of the development?

**Comment by unitygilles** [comment]
@angelbarrera92 Yes, I can start the work on this front. 👍 

@paurosello The deprecation is a good idea and I agree on the step by step.

**Comment by angelbarrera92** [comment]
> @angelbarrera92 Yes, I can start the work on this front. 👍
> 
> @paurosello The deprecation is a good idea and I agree on the step by step.

Go for it! Don't doubt pinging us if you have any doubt :)

**Comment by unitygilles** [comment]
@angelbarrera92 thanks, will do!

**Comment by angelbarrera92** [comment]
The dashboard feature has been released in v1.2.0.
What is missing is to manage in the same way the datasources.

**Comment by dubuc** [comment]
Cool, now that there is an approved implementation, adding datasources is going to be easy with that implementation reference. I should be able to work on that next week.

**Comment by unitygilles** [comment]
@angelbarrera92 Is there a hard preference on the dashboard `title` == `uid`? This enforcement limits the length and title of the dashboards to respect `uid` naming policy (i.e. no spaces, cannot have special characters, etc.).

If you do not respect the `uid` naming policy, you end up with the operator having the following errors:
```
Bad Input: `{'message': 'uid contains illegal characters'}`
```

**Comment by angelbarrera92** [comment]
> @angelbarrera92 Is there a hard preference on the dashboard `title` == `uid`? This enforcement limits the length and title of the dashboards to respect `uid` naming policy (i.e. no spaces, cannot have special characters, etc.).
> 
> If you do not respect the `uid` naming policy, you end up with the operator having the following errors:
> 
> ```
> Bad Input: `{'message': 'uid contains illegal characters'}`
> ```
> 
> We could add a field to the CRD that acts as the title?

Ciao @unitygilles!

The reason to override it was to enable the (easy) identification of a dashboard via grafana UI.
I mean... having the following CRD:

```yaml
apiVersion: grafana.k8spin.cloud/v1
kind: Dashboard
metadata:
  name: web-app-health
  namespace: default
spec:
  organizations:
  - example.com
  dashboard:
    name: example
    data: |
      {
        "type": "prometheus",
        "access": "proxy",
        "url": "http://prometheus.monitoring:9090"
      }
```

You can easily find the `example` dashboard in the Grafana UI.
(as you said, it has some restrictions)

All being said, I think adding a new attribute to the CRD should do the trick. Something like this would help:

```yaml
apiVersion: grafana.k8spin.cloud/v1
kind: Dashboard
metadata:
  name: web-app-health
  namespace: default
spec:
  organizations:
  - example.com
  dashboard:
    name: example
    title: My Example Dashboard
    data: |
      {
        "type": "prometheus",
        "access": "proxy",
        "url": "http://prometheus.monitoring:9090"
      }
```

Then, we can add the following rules to avoid breaking changes: 

- `spec.dashaboar.title` is an optional CRD field/attribute.
- If the user does not specify it, the `spec.dashaboar.name` is used as title (current behavior)
- If the user specify it, the `spec.dashaboar.title` is used as title.

What do you think @paurosello and @unitygilles?
