### ISSUE TITLE
Define role per organization in the User CR

### ISSUE THREAD

**Issue by angelbarrera92** [k8spin/grafana-multi-tenant-operator#39]
It would be nice to add a new feature in the User CRD to allow defining a different role other than `viewer`.

```yaml
---
apiVersion: grafana.k8spin.cloud/v1
kind: User
metadata:
  name: angelbarrera92
  namespace: monitoring
spec:
  email: angelbarrera92@yopmail.com
  organizations:
    - k8spin.cloud
```

Could be nice to have a new structure in the `organizations` list other than a list of strings:

```yaml
---
apiVersion: grafana.k8spin.cloud/v1
kind: User
metadata:
  name: angelbarrera92
  namespace: monitoring
spec:
  email: angelbarrera92@yopmail.com
  organizations:
    - name: k8spin.cloud
      role: admin
    - name: example.com
      role: viewer
    - name: default.io
```

If no role is set, `viewer` should be the default one. Consider that a User could be `viewer` in an organization and `admin` in a different one.
