### ISSUE TITLE
Enable to set a password to a User

### ISSUE THREAD

**Issue by angelbarrera92** [k8spin/grafana-multi-tenant-operator#40]
By default, every new user receives the [`changemeplease` password](https://github.com/k8spin/grafana-multi-tenant-operator/blob/master/grafana/user.py#L9)

It would be amazing if the password can be set from a `secret` object like you can configure environment variables from secrets in the container spec:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: angelbarrera92-pw
  namespace: monitoring
type: Opaque
stringData:
  password: jujuju
---
apiVersion: grafana.k8spin.cloud/v1
kind: User
metadata:
  name: angelbarrera92
  namespace: monitoring
spec:
  email: angelbarrera92@yopmail.com
  password:
    valueFrom:
      secretKeyRef:
        name: angelbarrera92-pw
        key: password
  organizations:
    - k8spin.cloud
```
